require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe UsersController do

  it "should authenticate with matching email and password" do
    user = Factory(:user, :email=>'geoff@example.com', :password => 'password')
    User.authenticate('geoff@example.com','password').should == user
  end

  it "should not authenticate with matching email and password" do
    user = Factory(:user, :email=>'geoff@example.com', :password => 'password')
    User.authenticate('geoff@example.com','password_wrong').should_not == user
  end

end

